# Hardcoded values for the season and plant type.
# These values can later be replaced with input() to allow user interaction.
season = "summer"
plant_type = "flower"

# Variable used to store all gardening advice generated by the program.
advice = ""

# Determine gardening advice based on the selected season.
if season == "summer":
    # Summer plants require regular watering and protection from excessive heat.
    advice += "Water your plants regularly and provide some shade.\n"
elif season == "winter":
    # Winter plants may need protection against frost and cold weather.
    advice += "Protect your plants from frost with covers.\n"
else:
    # Default message for unsupported seasons.
    advice += "No advice for this season.\n"

# Determine gardening advice based on the selected plant type.
if plant_type == "flower":
    # Flowers benefit from fertiliser to encourage healthy blooms.
    advice += "Use fertiliser to encourage blooms."
elif plant_type == "vegetable":
    # Vegetables are often affected by pests and should be monitored closely.
    advice += "Keep an eye out for pests!"
else:
    # Default message for unsupported plant types.
    advice += "No advice for this type of plant."

# Display the generated gardening advice to the user.
print(advice)

# TODO: Examples of possible features to add:
# - Add detailed comments explaining each block of code.
# - Refactor the code into functions for better readability and modularity.
# - Store advice in a dictionary for multiple plants and seasons.
# - Recommend plants based on the entered season.
